png(filename = "./github/ExData_Plotting1/Project 1/plot4.png")
par(mfrow=c(2,2))
plot(subsetdata$DateTime, subsetdata$Global_active_power, type= "l", ylab="Global Active Power", xlab="")
plot(subsetdata$DateTime, subsetdata$Voltage, type= "l", ylab="Voltage", xlab="datetime")
plot(subsetdata$DateTime, subsetdata$Sub_metering_1, type= "l", ylab="Energy Sub metering", xlab="")
lines(subsetdata$DateTime, subsetdata$Sub_metering_2, col="red")
lines(subsetdata$DateTime, subsetdata$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = 1:3, lty=1, lwd = 2.5)
plot(subsetdata$DateTime, subsetdata$Global_reactive_power, type= "l", ylab="Global_reactive_power", xlab="datetime")
dev.off()